### PR TITLE
[WIP] FireFox support

### PR DESCRIPTION
**Pull request by YuseiIto**
A few changes to support FireFox browser.

## Changes
- Inserted a random generated GUID as AddonID for Firefox (Reference: [browser_specific_settings - Mozilla | MDN]( https://developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings) )

## Environment
- This patch is tested on FireFox Browser 95.0 (64-bit), Mac OS 12.0.1

### CODE REVIEW

**Comment by YuseiIto** [comment]
Help wanted: I'd like to replace `chrome://extensions/shortcuts` to `about:addons` on firefox, but addons can't tell which browser is it working on because Chrome (and other `chrome.*` objects) doesn't implements `.getBrowser()` method.

An workaround for it could be like `typeof browser !== 'undefined'? 'Firefox':'Chrome'`, but it still cant'tell Safari and Firefox apart.

**Comment by mkobayashime** [comment]
@YuseiIto 
My apologies for the very late response.

Recently I'm working on the multi-browser support (for Chrome and Firefox for the moment), specifically in generating `manifest.json` from TypeScript file to put different values (sth like `browser_specific_settings` which you added in this PR) per browser in it. So the `manifest.json` file in the `public` directory itself will be gone in some near futere work, but I think merging the change you made is a good choice so far, respecting your contribution (Please allow me to remove it in the process described above later on).

BTW, I have no idea why the status checks are not running here. I suppose I would have to approve the running of workflows as you are an first-time contributor, but the button is not there at all. Can you try sth like force pushing after `commit --amend` or rebase to the latest master?

**Review by mkobayashime — APPROVED** [review]

**Comment by YuseiIto** [comment]
(oops, I accidentally merged all the following commits on main here... I'm terribly sorry how it pollutes the commit tree.)
But yes, I suppose this branch is now up-to-date with the latest `main` now.

>I think merging the change you made is a good choice so far, respecting your contribution

I really appreciate your kindness. Please just feel free and don't hesitate to remove my codes, as you mentioned.

**Comment by mkobayashime** [comment]
@YuseiIto 
I believe I figured it out. Just updated the `on` attribute of the workflow file, so the status checks will run in PRs from forked repos (it still needs my approval though) from now. Please rebase and force push again.
I can't merge a PR with a number of dead commits duplicated with `main`, so I'd like you to rebase it onto latest `mkobayashime:main` so that this PR contains exactly one commit.

**Pull request merged**
